name: 'Process Julia coverage files'
description: 'Convert Julia coverage files into a lcov file'
author: 'David Anthoff'

branding:
  icon: 'settings'
  color: 'gray-dark'

inputs:
  directories:
    description: 'Comma-separated list of directories to look for coverage information (e.g. `src,examples`)'
    required: false
    default: 'src,ext'

runs:
  using: 'composite'
  steps:
    - run: julia --color=yes "$GITHUB_ACTION_PATH"/main.jl
      shell: bash
      env:
        INPUT_DIRECTORIES: ${{ inputs.directories }}
