name: 'Process Julia coverage files'
description: 'Convert Julia coverage files into a lcov file'
author: 'David Anthoff'

branding:
  icon: 'settings'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: julia --color=yes "$GITHUB_ACTION_PATH"/main.jl
      shell: bash
